### ISSUE TITLE
Given the environment to run  alloy command line 

### ISSUE THREAD

**Issue by rootsongjc** [olliecoleman/alloy#1]
alloy command line error because of smtp port connection refused

**Code line**

```
app/mailer/smtp.go:14:	port, err := strconv.Atoi(envy.Get("SMTP_PORT", "1025"))
```

**logs**

```
$ alloy help
panic: dial tcp 127.0.0.1:1025: getsockopt: connection refused

goroutine 1 [running]:
github.com/olliecoleman/alloy/app/mailer.setupSMTP(0x15c992a, 0xb)
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/app/mailer/smtp.go:28 +0x26f
github.com/olliecoleman/alloy/app/mailer.init.1()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/app/mailer/mailer.go:37 +0x76
github.com/olliecoleman/alloy/app/mailer.init()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/app/mailer/support.go:32 +0x76
github.com/olliecoleman/alloy/app/handlers.init()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/app/handlers/support_messages.go:59 +0x89
github.com/olliecoleman/alloy/app/router.init()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/app/router/router.go:132 +0x62
github.com/olliecoleman/alloy/cmd.init()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/cmd/server.go:39 +0x91
main.init()
	/Users/jimmy/Workspace/go/src/github.com/olliecoleman/alloy/main.go:26 +0x53
```

**Comment by olliecoleman** [comment]
Hi, Please create the following environment variables before starting the server
```
SMTP_HOST=127.0.0.1
SMTP_PORT=1025
SMTP_USERNAME=__REPLACE___
SMTP_PASSWORD=__REPLACE___
``` 

I'll also add this to the README shortly.

For dev environment, you can use something like mailcatcher for viewing the sent emails.

**Comment by rootsongjc** [comment]
Thank you @olliecoleman I use [MailHog](https://github.com/mailhog/MailHog) instead of MailCatcher.
Env `DATABASE_URL` must specify

**Comment by olliecoleman** [comment]
Closing this issue as I've added this to the README file.
